import { useState } from "react";
import { Archive, CalendarDays, ChevronDown, Cloud, FolderTree, Info, Workflow } from "lucide-react";
import { useSearchParams } from "react-router-dom";
import feishuWorkflowData from "../data/feishuWorkflow.json";
import feishuArtifactsData from "../data/feishuArtifacts.json";
import validationTasks from "../data/validationTasks.json";
import decisionLedger from "../data/decisionLedger.json";
import type { FeishuArtifact, FeishuWorkflow as FeishuWorkflowData } from "../types";
import StatusBadge, { getStatusLabel } from "../components/StatusBadge";
import PageHeader from "../components/PageHeader";
import PageDataLineage from "../components/PageDataLineage";

const artifacts = feishuArtifactsData as FeishuArtifact[];
const feishuWorkflow = feishuWorkflowData as FeishuWorkflowData;

export default function FeishuWorkflow() {
  const [searchParams] = useSearchParams();
  const types = ["全部", ...Array.from(new Set(artifacts.map((item) => item.feishuType)))];
  const [type, setType] = useState(types[0]);
  const [showBoundary, setShowBoundary] = useState(false);
  const requestedArtifact = searchParams.get("focus");
  const [openArtifact, setOpenArtifact] = useState<string | null>(artifacts.some((item) => item.id === requestedArtifact) ? requestedArtifact : artifacts[0]?.id ?? null);
  const [openLedger, setOpenLedger] = useState<string | null>(decisionLedger[decisionLedger.length - 1]?.id ?? null);
  const visible = type === types[0] ? artifacts : artifacts.filter((item) => item.feishuType === type);

  return (
    <div className="space-y-6">
      <PageHeader eyebrow="07 / Collaboration Overview" title="飞书协作全景与知识沉淀" icon={Archive}
        description="飞书贯穿数据采集、证据审核、评审协作和知识复用；本页汇总当前 Run 的协作资产，不是流程末端的导出页。"
        action={<button type="button" onClick={() => setShowBoundary((value) => !value)} className="secondary-button"><Info size={15} /> {showBoundary ? "收起协作边界" : "查看协作边界"}</button>} />

      <PageDataLineage page="feishu-workflow" />

      <section className="border border-slate-200 bg-white p-4"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><Cloud className="text-blue-700" size={20} /><div><div className="text-sm font-semibold text-ink">真实飞书资产 + 已审核快照 + Proposal Mock</div><div className="mt-1 text-xs text-slate-500">{getStatusLabel(feishuWorkflow.currentMode)} · {getStatusLabel(feishuWorkflow.runStatus)}</div></div></div><span className="data-boundary">网页只读 · 未接入实时前端 API</span></div>{showBoundary ? <div className="mt-4 grid gap-px border border-slate-200 bg-slate-200 text-xs leading-5 md:grid-cols-3"><div className="bg-emerald-50 p-3"><div className="font-semibold text-emerald-800">真实飞书资产</div><p className="mt-1 text-slate-600">数据采集 Base、填写说明文档和 Proposal PRD 文档已存在。</p></div><div className="bg-blue-50 p-3"><div className="font-semibold text-blue-800">已审核快照</div><p className="mt-1 text-slate-600">CLI 审核后的结构化数据进入本地 JSON，驱动七页演示。</p></div><div className="bg-slate-50 p-3"><div className="font-semibold text-slate-700">Proposal Mock</div><p className="mt-1 text-slate-600">任务、会议、知识库回写仅展示目标结构，不宣称已实时创建。</p></div></div> : null}</section>

      <section><div className="mb-3"><h3 className="section-title">当前 Run 协作资产地图</h3><p className="section-subtitle">飞书从项目治理开始承载输入、审核、决策与复用；本页只做跨阶段汇总</p></div><div className="grid grid-cols-1 gap-px overflow-hidden border border-slate-200 bg-slate-200 md:grid-cols-2 xl:grid-cols-4">{feishuWorkflow.layers.map((layer, index) => <article key={layer.id} className="bg-white p-4"><div className="flex items-center justify-between"><span className="flex h-7 w-7 items-center justify-center rounded bg-slate-100 text-xs font-semibold text-slate-600">{index + 1}</span><Workflow size={16} className="text-blue-700" /></div><h3 className="mt-4 font-semibold text-ink">{layer.name}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{layer.description}</p><div className="mt-3 flex flex-wrap gap-1">{layer.feishuObjects.map((item) => <span key={item} className="rounded bg-slate-100 px-2 py-1 text-[11px] text-slate-600">{item}</span>)}</div></article>)}</div></section>

      <section><div className="toolbar">{types.map((item) => <button key={item} aria-pressed={type === item} onClick={() => setType(item)} className={`filter-button ${type === item ? "filter-button-active" : ""}`}>{item}</button>)}</div><div className="grid grid-cols-1 gap-px border-x border-b border-slate-200 bg-slate-200 lg:grid-cols-2">{visible.map((artifact) => <article key={artifact.id} className="bg-white p-4"><button aria-expanded={openArtifact === artifact.id} onClick={() => setOpenArtifact(openArtifact === artifact.id ? null : artifact.id)} className="w-full text-left"><div className="flex items-start justify-between gap-3"><div><div className="text-xs font-semibold text-blue-700">{artifact.feishuType}</div><h3 className="mt-1 font-semibold text-ink">{artifact.name}</h3></div><div className="flex items-center gap-2"><StatusBadge status={artifact.mockStatus} /><ChevronDown size={15} className={`text-slate-400 transition ${openArtifact === artifact.id ? "rotate-180" : ""}`} /></div></div><p className="mt-3 text-sm leading-6 text-slate-600">{artifact.businessValue}</p><div className="mt-3 text-xs text-slate-400">{artifact.sourcePages.join(" / ")}</div></button>{openArtifact === artifact.id ? <div className="mt-4 border-t border-slate-100 pt-3"><div className="text-[11px] font-semibold uppercase text-slate-400">产物内容</div><div className="mt-2 flex flex-wrap gap-1.5">{artifact.content.map((item) => <span key={item} className="rounded border border-slate-200 bg-slate-50 px-2 py-1 text-xs text-slate-600">{item}</span>)}</div></div> : null}</article>)}</div></section>

      <section className="grid grid-cols-1 gap-5 xl:grid-cols-2">
        <article className="panel"><div className="flex items-start justify-between gap-3"><div><div className="section-kicker"><CalendarDays size={14} /> 二次评审协作</div><h3 className="mt-2 text-lg font-semibold text-ink">{feishuWorkflow.reviewMeeting.title}</h3></div><StatusBadge status={feishuWorkflow.reviewMeeting.mockStatus} /></div><p className="mt-2 text-xs text-slate-500">{feishuWorkflow.reviewMeeting.schedule}</p><div className="mt-4"><div className="text-xs font-semibold text-slate-500">议程</div><ol className="mt-2 space-y-2 text-sm leading-6 text-slate-700">{feishuWorkflow.reviewMeeting.agenda.map((item, index) => <li key={item} className="flex gap-2"><span className="text-blue-700">0{index + 1}</span><span>{item}</span></li>)}</ol></div><div className="mt-4 border-t border-slate-100 pt-3"><div className="text-xs font-semibold text-slate-500">参与角色与预期产物</div><p className="mt-2 text-xs leading-5 text-slate-600">{feishuWorkflow.reviewMeeting.participants.join(" / ")}</p><div className="mt-2 flex flex-wrap gap-1.5">{feishuWorkflow.reviewMeeting.expectedOutputs.map((item) => <span key={item} className="rounded bg-slate-100 px-2 py-1 text-[11px] text-slate-600">{item}</span>)}</div></div></article>
        <article className="panel"><div className="flex items-start justify-between gap-3"><div><div className="section-kicker"><FolderTree size={14} /> 知识归档树</div><h3 className="mt-2 text-sm font-semibold leading-6 text-ink">{feishuWorkflow.knowledgeArchive.root}</h3></div><StatusBadge status={feishuWorkflow.knowledgeArchive.mockStatus} /></div><div className="mt-4 divide-y divide-slate-100 border-y border-slate-100">{feishuWorkflow.knowledgeArchive.nodes.map((node) => <div key={node.id} className="grid gap-2 py-3 sm:grid-cols-[minmax(0,1fr)_auto]"><div><div className="text-sm font-semibold text-ink">{node.name}</div><div className="mt-1 text-xs text-slate-500">{node.artifactType}</div><p className="mt-1 text-xs leading-5 text-slate-600">{node.summary}</p></div><StatusBadge status={node.mockStatus} /></div>)}</div></article>
      </section>

      <section className="grid grid-cols-1 gap-5 xl:grid-cols-2"><div><div className="mb-3 flex items-end justify-between"><div><h3 className="section-title">验证任务</h3><p className="section-subtitle">PRD 草案进入下一轮验证的责任对象</p></div><span className="text-xs text-slate-500">{validationTasks.length} 项任务</span></div><div className="divide-y divide-slate-200 border-y border-slate-200 bg-white">{validationTasks.map((task) => <div key={task.id} className="grid grid-cols-1 gap-2 px-4 py-3 sm:grid-cols-[minmax(0,1fr)_auto]"><div><h4 className="text-sm font-semibold text-ink">{task.title}</h4><p className="mt-1 text-xs text-slate-500">{task.ownerRole.join(" / ")}</p></div><div className="flex items-center gap-2"><StatusBadge status={task.priority} /><StatusBadge status={task.status} /></div></div>)}</div></div>
        <div><div className="mb-3"><h3 className="section-title">决策台账</h3><p className="section-subtitle">保留结论、依据、风险和下一动作</p></div><div className="divide-y divide-slate-200 border-y border-slate-200 bg-white">{decisionLedger.map((item) => <article key={item.id} className="px-4 py-3"><button aria-expanded={openLedger === item.id} onClick={() => setOpenLedger(openLedger === item.id ? null : item.id)} className="flex w-full items-start justify-between gap-3 text-left"><div><div className="text-xs font-semibold text-blue-700">{item.day} · {item.stage}</div><h4 className="mt-1 text-sm font-semibold leading-6 text-ink">{item.decision}</h4></div><ChevronDown size={16} className={`mt-1 shrink-0 text-slate-400 transition ${openLedger === item.id ? "rotate-180" : ""}`} /></button>{openLedger === item.id ? <dl className="mt-3 grid gap-3 border-l-2 border-blue-200 pl-3 text-xs leading-5 sm:grid-cols-2"><div><dt className="font-semibold">依据</dt><dd className="text-slate-600">{item.basis}</dd></div><div><dt className="font-semibold">风险</dt><dd className="text-slate-600">{item.risk}</dd></div><div><dt className="font-semibold">责任人</dt><dd className="text-slate-600">{item.ownerRole}</dd></div><div><dt className="font-semibold">下一步</dt><dd className="text-slate-600">{item.nextAction}</dd></div></dl> : null}</article>)}</div></div></section>
    </div>
  );
}
